### ISSUE TITLE
search ability in UI

### ISSUE THREAD

**Issue by yeya24** [polarsignals/issues#12]
As @brancz mentioned, this is already available in the default pprof UI.

![image](https://user-images.githubusercontent.com/25150124/120387579-18e0dd80-c2f8-11eb-992e-05794f3f488e.png)

It would be nice to support this feature in the PolarSignals UI, too.

Another thing I am thinking about is more related to Conprof itself. This builtin search bar filters samples in the runtime but the whole profile is still stored in the TSDB.  As a user, I don't need the whole profile. I just want to look at some important samples (for example, samples from package xxx).

**Comment by brancz** [comment]
Regarding your later point, is the storage part really the important part here? If I understand correctly, you want to just hide all of the noise that you're not currently interested in, correct? I very much agree on hiding the "currently not important" noise, since you're probably focusing on one specific part to optimize.

**Comment by yeya24** [comment]
Yes, that's exactly what I want.

**Comment by brancz** [comment]
This is available now using the filter-by-function functionality. Let us know what you think!
