### ISSUE TITLE
Clicking on latest profile returns an error

### ISSUE THREAD

**Issue by lilic** [polarsignals/issues#9]
I often am interested in the latest profile, especially if I am running a scale test or in the middle of an incident, etc. But somehow latest profile returns an error always.

It's not a huge problem, as in a few seconds I can get the profile, but would be still nice for a better UX.

<img width="940" alt="Screenshot 2021-04-09 at 11 17 30" src="https://user-images.githubusercontent.com/6232346/114158906-82aabf80-9925-11eb-9894-fec92f431969.png">

Thank you!

**Comment by brancz** [comment]
Thank you for opening the issue! What's happening here is that the backend seeks to the next available sample, and I suspect that our metrics backend, which is Prometheus based, does some interpolation and the timestamp of the rendered graph sample is slightly ahead of the requested one. We should probably change our seek algorithm to allow for a small tolerance and choose the closest profile, instead of always the next.

**Comment by brancz** [comment]
This has been fixed!
